const countries = {
    "am-ET" : "Amharic",
    "ar-SA" : "Arabic",
    "be-BY" : "Bielarur",
    "mo-MA": "Moroccan",
    "mo-MA": "Morocco",
    "br-BR": "Brazilian",
    "br-BR": "Brazilian",
    "ch-ZH": "Chinese",
    "br-GB": "Britain",
    "fr-FJ": "French",
    "ge-DE": "Germany",
    "hi-HI": "Hindi",
    "it-IT": "Italian",
    "ko-KO": "Korean",
    "po-TD": "Portuguese",
    "sp-ES": "Spain",
    "en-GB": "English",
}